import ExcelJS from 'exceljs';import {pool} from '@/lib/db';
const norm=(v:any)=>String(v??'').trim();
function cellValue(row:ExcelJS.Row, map:Record<string,number>, name:string){return row.getCell(map[name]||0).value}
export async function POST(req:Request){
  const fd=await req.formData();const file=fd.get('file');if(!(file instanceof File))return Response.json({error:'Pilih file Excel terlebih dahulu.'},{status:400});
  const wb=new ExcelJS.Workbook();await wb.xlsx.load(Buffer.from(await file.arrayBuffer()) as any);const ws=wb.worksheets[0];if(!ws)return Response.json({error:'Sheet Excel tidak ditemukan.'},{status:400});
  const headers:Record<string,number>={};ws.getRow(1).eachCell((c,col)=>headers[norm(c.value).toLowerCase()]=col);
  const aliases=(...names:string[])=>{for(const n of names){const x=headers[n.toLowerCase()];if(x)return x}return 0};
  const map={bomNo:aliases('BOM No','No BOM'),name:aliases('Formula Name','Nama Formula'),productNo:aliases('Product Item No','No Barang Jadi'),productName:aliases('Product Name','Nama Barang Jadi'),outputQty:aliases('Output Qty','Qty Output'),matNo:aliases('Material Item No','No Bahan'),matName:aliases('Material Name','Nama Bahan'),matQty:aliases('Material Qty','Qty Bahan'),matUnit:aliases('Material Unit','Satuan Bahan'),costName:aliases('Cost Name','Nama Biaya'),accountNo:aliases('Account No','No Akun'),costAmount:aliases('Cost Amount','Nilai Biaya'),notes:aliases('Notes','Catatan')};
  if(!map.bomNo||!map.name||!map.productNo)return Response.json({error:'Format Excel tidak sesuai template BOM.'},{status:400});
  const groups=new Map<string,any>();for(let i=2;i<=ws.rowCount;i++){const row=ws.getRow(i);const no=norm(row.getCell(map.bomNo).value);if(!no)continue;let g=groups.get(no);if(!g){g={bomNo:no,name:norm(row.getCell(map.name).value),productItemNo:norm(row.getCell(map.productNo).value),productName:norm(row.getCell(map.productName).value),outputQty:Number(row.getCell(map.outputQty).value||1),notes:norm(row.getCell(map.notes).value),materials:[],costs:[]};groups.set(no,g)}const mn=norm(row.getCell(map.matNo).value);if(mn)g.materials.push({itemNo:mn,itemName:norm(row.getCell(map.matName).value)||mn,qty:Number(row.getCell(map.matQty).value||0),unit:norm(row.getCell(map.matUnit).value)});const cn=norm(row.getCell(map.costName).value);if(cn)g.costs.push({costName:cn,accountNo:norm(row.getCell(map.accountNo).value),amount:Number(row.getCell(map.costAmount).value||0)});}
  const c=await pool.connect();let count=0;try{await c.query('BEGIN');for(const g of groups.values()){const ex=await c.query('SELECT id FROM boms WHERE bom_no=$1',[g.bomNo]);let id;if(ex.rows[0]){id=ex.rows[0].id;await c.query(`UPDATE boms SET name=$2,product_item_no=$3,product_name=$4,output_qty=$5,notes=$6,updated_at=NOW() WHERE id=$1`,[id,g.name,g.productItemNo,g.productName,g.outputQty,g.notes||null]);await c.query('DELETE FROM bom_materials WHERE bom_id=$1',[id]);await c.query('DELETE FROM bom_costs WHERE bom_id=$1',[id]);}else{id=(await c.query(`INSERT INTO boms(bom_no,name,product_item_no,product_name,output_qty,notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[g.bomNo,g.name,g.productItemNo,g.productName,g.outputQty,g.notes||null])).rows[0].id;}for(const m of g.materials)if(m.qty>0)await c.query(`INSERT INTO bom_materials(bom_id,item_no,item_name,qty,unit) VALUES($1,$2,$3,$4,$5)`,[id,m.itemNo,m.itemName,m.qty,m.unit||null]);for(const k of g.costs)await c.query(`INSERT INTO bom_costs(bom_id,cost_name,account_no,amount) VALUES($1,$2,$3,$4)`,[id,k.costName,k.accountNo||null,k.amount]);count++;}await c.query('COMMIT');return Response.json({ok:true,count,message:`${count} BOM berhasil diimpor.`});}catch(e:any){await c.query('ROLLBACK');return Response.json({error:e.message},{status:400})}finally{c.release()}
}
