import {requireApiPermission} from '@/lib/auth';
import ExcelJS from 'exceljs';import {pool} from '@/lib/db';
const norm=(v:any)=>String(v??'').trim();
export async function POST(req:Request){const auth=await requireApiPermission('bom.import');if(!auth.ok)return auth.response;
 const fd=await req.formData();const file=fd.get('file');if(!(file instanceof File))return Response.json({error:'Pilih file Excel terlebih dahulu.'},{status:400});
 const wb=new ExcelJS.Workbook();await wb.xlsx.load(Buffer.from(await file.arrayBuffer()) as any);const ws=wb.worksheets[0];if(!ws)return Response.json({error:'Sheet Excel tidak ditemukan.'},{status:400});
 const headers:Record<string,number>={};ws.getRow(1).eachCell((c,col)=>headers[norm(c.value).toLowerCase()]=col);const aliases=(...names:string[])=>{for(const n of names){const x=headers[n.toLowerCase()];if(x)return x}return 0};
 const map={bomNo:aliases('BOM No','No BOM'),name:aliases('Formula Name','Nama Formula'),productNo:aliases('Product Item No','No Barang Jadi'),outputQty:aliases('Output Qty','Qty Output'),matNo:aliases('Material Item No','No Bahan'),matQty:aliases('Material Qty','Qty Bahan'),costName:aliases('Cost Name','Nama Biaya'),accountNo:aliases('Account No','No Akun'),costAmount:aliases('Cost Amount','Nilai Biaya'),notes:aliases('Notes','Catatan')};if(!map.bomNo||!map.name||!map.productNo)return Response.json({error:'Format Excel tidak sesuai template BOM.'},{status:400});
 const groups=new Map<string,any>();for(let i=2;i<=ws.rowCount;i++){const row=ws.getRow(i);const no=norm(row.getCell(map.bomNo).value);if(!no)continue;let g=groups.get(no);if(!g){g={bomNo:no,name:norm(row.getCell(map.name).value),productItemNo:norm(row.getCell(map.productNo).value),outputQty:Number(row.getCell(map.outputQty).value||1),notes:norm(row.getCell(map.notes).value),materials:[],costs:[]};groups.set(no,g)}const mn=norm(row.getCell(map.matNo).value);if(mn)g.materials.push({itemNo:mn,qty:Number(row.getCell(map.matQty).value||0)});const cn=norm(row.getCell(map.costName).value);if(cn)g.costs.push({costName:cn,accountNo:norm(row.getCell(map.accountNo).value),amount:Number(row.getCell(map.costAmount).value||0)});}
 const c=await pool.connect();let count=0;try{await c.query('BEGIN');for(const g of groups.values()){const prod=await c.query('SELECT item_no,name,unit FROM items_cache WHERE organization_id=$1 AND item_no=$2 LIMIT 1',[auth.user.organization_id,g.productItemNo]);if(!prod.rows[0])throw new Error(`Barang jadi ${g.productItemNo} belum ditemukan di master Accurate.`);const ex=await c.query('SELECT id FROM boms WHERE organization_id=$1 AND bom_no=$2',[auth.user.organization_id,g.bomNo]);let id;if(ex.rows[0]){id=ex.rows[0].id;await c.query(`UPDATE boms SET name=$3,product_item_no=$4,product_name=$5,product_unit=$6,output_qty=$7,notes=$8,updated_at=NOW() WHERE id=$1 AND organization_id=$2`,[id,auth.user.organization_id,g.name,g.productItemNo,prod.rows[0].name,prod.rows[0].unit||null,g.outputQty,g.notes||null]);await c.query('DELETE FROM bom_materials WHERE bom_id=$1',[id]);await c.query('DELETE FROM bom_costs WHERE bom_id=$1',[id]);}else{id=(await c.query(`INSERT INTO boms(organization_id,bom_no,name,product_item_no,product_name,product_unit,output_qty,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[auth.user.organization_id,g.bomNo,g.name,g.productItemNo,prod.rows[0].name,prod.rows[0].unit||null,g.outputQty,g.notes||null])).rows[0].id;}for(const m of g.materials){if(m.qty<=0)continue;const item=await c.query('SELECT name,unit FROM items_cache WHERE organization_id=$1 AND item_no=$2 LIMIT 1',[auth.user.organization_id,m.itemNo]);if(!item.rows[0])throw new Error(`Bahan baku ${m.itemNo} belum ditemukan di master Accurate.`);await c.query(`INSERT INTO bom_materials(bom_id,item_no,item_name,qty,unit) VALUES($1,$2,$3,$4,$5)`,[id,m.itemNo,item.rows[0].name,m.qty,item.rows[0].unit||null])}for(const k of g.costs)await c.query(`INSERT INTO bom_costs(bom_id,cost_name,account_no,amount) VALUES($1,$2,$3,$4)`,[id,k.costName,k.accountNo||null,k.amount]);count++;}await c.query('COMMIT');return Response.json({ok:true,count,message:`${count} BOM berhasil diimpor. Nama barang dan satuan mengikuti master Accurate.`})}catch(e:any){await c.query('ROLLBACK');return Response.json({error:e.message},{status:400})}finally{c.release()}}
