'use client';import{useEffect,useState}from'react';import{useRouter}from'next/navigation';
export default function AccuratePanel({connected,databaseAlias,email}:{connected:boolean,databaseAlias?:string,email?:string}){
 const[dbs,setDbs]=useState<any[]>([]);const[msg,setMsg]=useState('');const[stats,setStats]=useState<any>({items:0,warehouses:0,accounts:0});const r=useRouter();
 async function status(){const x=await fetch('/api/accurate/master-status');if(x.ok)setStats(await x.json())}useEffect(()=>{status()},[]);
 async function load(){setMsg('Mengambil daftar database...');const x=await fetch('/api/accurate/databases');const j=await x.json();if(x.ok){setDbs(j.d||j.data||[]);setMsg('')}else setMsg(j.error||'Gagal mengambil database')}
 async function open(d:any){setMsg('Menghubungkan database dan menyiapkan data...');const x=await fetch('/api/accurate/open-db',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:d.id,alias:d.alias||d.name})});const j=await x.json();setMsg(x.ok?(j.warning||`Terhubung ke ${d.alias||d.name}`):j.error||'Gagal');if(x.ok){await status();r.refresh()}}
 async function sync(){setMsg('Menyinkronkan data Accurate...');const x=await fetch('/api/accurate/sync-master',{method:'POST'});const j=await x.json();setMsg(x.ok?j.message:j.error||'Sinkronisasi gagal');if(x.ok){await status();r.refresh()}}
 return <div className="stack"><div className="grid two"><div className="card"><h2 className="section-title">Koneksi Accurate Online</h2>{connected?<div className="notice ok"><b>✓ Sudah terhubung</b><div className="small muted">{email||'Akun Accurate'}{databaseAlias?` · ${databaseAlias}`:''}</div></div>:<><div className="notice">Hubungkan BOM-JOBCOSTING dengan Accurate Online.</div><a className="btn green" style={{display:'inline-block',marginTop:12}} href="/api/accurate/oauth/start">Connect Accurate Online</a></>}</div><div className="card"><h2 className="section-title">Database Accurate</h2><button className="btn" onClick={load} disabled={!connected}>Tampilkan Database</button><div className="stack" style={{marginTop:12}}>{dbs.map(d=><div className="row" key={d.id} style={{justifyContent:'space-between',borderBottom:'1px solid #eee',paddingBottom:8}}><div><b>{d.alias||d.name||`Database ${d.id}`}</b></div><button className="btn secondary" onClick={()=>open(d)}>Pilih</button></div>)}</div></div></div>
 <div className="card"><div className="row wrap" style={{justifyContent:'space-between'}}><div><h2 className="section-title" style={{marginBottom:4}}>Data dari Accurate</h2><div className="muted small">Data ini dipakai sebagai pilihan saat membuat BOM dan Work Order.</div></div><button className="btn green" onClick={sync} disabled={!databaseAlias}>Sinkronkan Sekarang</button></div><div className="grid three" style={{marginTop:14}}><div className="stat-mini"><b>{stats.items}</b><span>Barang</span></div><div className="stat-mini"><b>{stats.warehouses}</b><span>Gudang</span></div><div className="stat-mini"><b>{stats.accounts}</b><span>Akun</span></div></div>{msg&&<div className="notice" style={{marginTop:12}}>{msg}</div>}</div></div>
}
