'use client';
import{useState}from'react';import{useRouter}from'next/navigation';

type Item={item_no:string,name:string,unit?:string};
type Account={account_no:string,name:string,account_type?:string};
type MaterialLine={itemNo:string,itemName:string,qty:string,unit:string};
type CostLine={costName:string,accountNo:string,amount:string};
type InitialMaterial={item_no?:string,itemNo?:string,item_name?:string,itemName?:string,qty?:string|number,unit?:string};
type InitialCost={cost_name?:string,costName?:string,account_no?:string,accountNo?:string,amount?:string|number};
const formatMoney=(v:string|number)=>{const n=Number(String(v??'').replace(/\D/g,''));return Number.isFinite(n)&&n?new Intl.NumberFormat('id-ID').format(n):''};
const rawMoney=(v:string)=>v.replace(/\D/g,'');
export default function BomForm({items=[],accounts=[],initial,id}:{items?:Item[],accounts?:Account[],initial?:any,id?:string}){
 const r=useRouter();const initialProductUnit=initial?.product_unit||items.find(i=>i.item_no===initial?.product_item_no)?.unit||'';const[b,setB]=useState({bomNo:initial?.bom_no||'',name:initial?.name||'',productItemNo:initial?.product_item_no||'',productName:initial?.product_name||'',productUnit:initialProductUnit,outputQty:String(initial?.output_qty||1),notes:initial?.notes||''});
 const initialMaterials:InitialMaterial[]=initial?.materials||[{item_no:'',item_name:'',qty:1,unit:''}];
 const initialCosts:InitialCost[]=initial?.costs||[{cost_name:'Labor',account_no:'',amount:0}];
 const[materials,setMaterials]=useState<MaterialLine[]>(initialMaterials.map((m:InitialMaterial)=>({itemNo:m.item_no||m.itemNo||'',itemName:m.item_name||m.itemName||'',qty:String(m.qty??1),unit:m.unit||''})));
 const[costs,setCosts]=useState<CostLine[]>(initialCosts.map((k:InitialCost)=>({costName:k.cost_name||k.costName||'',accountNo:k.account_no||k.accountNo||'',amount:String(k.amount??0)})));const[msg,setMsg]=useState('');
 const set=(k:string,v:string)=>setB({...b,[k]:v});
 function pickProduct(no:string){const x=items.find(i=>i.item_no===no);setB({...b,productItemNo:no,productName:x?.name||'',productUnit:x?.unit||''})}
 function pickMaterial(i:number,no:string){const x=items.find(z=>z.item_no===no);const a=[...materials];a[i]={...a[i],itemNo:no,itemName:x?.name||'',unit:x?.unit||a[i].unit};setMaterials(a)}
 async function save(){setMsg('Menyimpan...');const res=await fetch(id?`/api/boms/${id}`:'/api/boms',{method:id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...b,materials,costs})});const j=await res.json();if(!res.ok)return setMsg(j.error||'Gagal menyimpan');r.push('/boms');r.refresh()}
 return <div className="stack"><div className="card"><div className="grid two"><label>BOM No<input className="input" value={b.bomNo} onChange={e=>set('bomNo',e.target.value)} placeholder="BOM-0002"/></label><label>Nama Formula<input className="input" value={b.name} onChange={e=>set('name',e.target.value)}/></label><label>Barang Jadi<select className="select" value={b.productItemNo} onChange={e=>pickProduct(e.target.value)}><option value="">-- pilih barang Accurate --</option>{items.map(x=><option key={x.item_no} value={x.item_no}>{x.item_no} — {x.name}</option>)}</select></label><label>Nama Barang Jadi<input className="input" value={b.productName} readOnly placeholder="Terisi otomatis dari Accurate"/></label><label>Satuan Barang Jadi<input className="input" value={b.productUnit} readOnly placeholder="Dari Accurate"/></label><label>Output Qty<input className="input" type="number" step="0.0001" value={b.outputQty} onChange={e=>set('outputQty',e.target.value)}/></label><label>Catatan<input className="input" value={b.notes} onChange={e=>set('notes',e.target.value)}/></label></div>{items.length===0&&<div className="notice danger" style={{marginTop:12}}>Daftar barang belum tersedia. Hubungkan Accurate Online, pilih database, lalu sinkronkan data master.</div>}</div>
 <div className="card"><h2 className="section-title">Bahan Baku</h2>{materials.map((m:MaterialLine,i:number)=><div className="grid material-grid" key={i} style={{marginBottom:8}}><select className="select" value={m.itemNo} onChange={e=>pickMaterial(i,e.target.value)}><option value="">-- pilih barang --</option>{items.map(x=><option key={x.item_no} value={x.item_no}>{x.item_no} — {x.name}</option>)}</select><input className="input" value={m.itemName} readOnly placeholder="Nama barang"/><input className="input" type="number" step="0.0001" value={m.qty} onChange={e=>{const x=[...materials];x[i]={...m,qty:e.target.value};setMaterials(x)}}/><input className="input" value={m.unit} readOnly placeholder="Dari Accurate"/><button className="btn red iconbtn" type="button" onClick={()=>setMaterials(materials.filter((_:MaterialLine,n:number)=>n!==i))}>×</button></div>)}<button className="btn secondary" type="button" onClick={()=>setMaterials([...materials,{itemNo:'',itemName:'',qty:'1',unit:''}])}>+ Bahan</button></div>
 <div className="card"><h2 className="section-title">Biaya Lain</h2>{costs.map((k:CostLine,i:number)=><div className="grid cost-grid" key={i} style={{marginBottom:8}}><input className="input" placeholder="Nama biaya" value={k.costName} onChange={e=>{const x=[...costs];x[i]={...k,costName:e.target.value};setCosts(x)}}/><select className="select" value={k.accountNo} onChange={e=>{const acc=accounts.find(a=>a.account_no===e.target.value);const x=[...costs];x[i]={...k,accountNo:e.target.value,costName:k.costName.trim()?k.costName:(acc?.name||'')};setCosts(x)}}><option value="">-- pilih akun Accurate --</option>{accounts.map(x=><option key={x.account_no} value={x.account_no}>{x.account_no} — {x.name}</option>)}</select><input className="input" inputMode="numeric" placeholder="Nilai" value={formatMoney(k.amount)} onChange={e=>{const x=[...costs];x[i]={...k,amount:rawMoney(e.target.value)};setCosts(x)}}/><button className="btn red iconbtn" type="button" onClick={()=>setCosts(costs.filter((_:CostLine,n:number)=>n!==i))}>×</button></div>)}<button className="btn secondary" type="button" onClick={()=>setCosts([...costs,{costName:'',accountNo:'',amount:'0'}])}>+ Biaya</button></div>
 <div className="row"><button className="btn green" onClick={save}>{id?'Update BOM':'Save BOM'}</button>{msg&&<span className="muted">{msg}</span>}</div></div>
}
