'use client';import{useState}from'react';import{useRouter}from'next/navigation';
export default function WoForm({boms,warehouses=[],initial,id}:{boms:any[];warehouses?:any[];initial?:any;id?:string}){
 const r=useRouter();const[b,setB]=useState({woNo:initial?.wo_no||'',bomId:String(initial?.bom_id||boms[0]?.id||''),plannedQty:String(initial?.planned_qty||1),warehouseName:initial?.warehouse_name||warehouses[0]?.name||'',woDate:initial?String(initial.wo_date).slice(0,10):new Date().toISOString().slice(0,10),notes:initial?.notes||''});
 const[materials,setMaterials]=useState((initial?.materials||[]).map((m:any)=>({itemNo:m.item_no,itemName:m.item_name,qty:String(m.qty),unit:m.unit||''})));const[costs,setCosts]=useState((initial?.costs||[]).map((k:any)=>({costName:k.cost_name,accountNo:k.account_no||'',amount:String(k.amount)})));const[msg,setMsg]=useState('');
 async function save(){setMsg(id?'Menyimpan perubahan...':'Membuat WO...');const payload=id?{...b,materials,costs}:b;const res=await fetch(id?`/api/work-orders/${id}`:'/api/work-orders',{method:id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await res.json();if(!res.ok)return setMsg(j.error||'Gagal');r.push('/work-orders');r.refresh()}
 return <div className="stack"><div className="card" style={{maxWidth:900}}><div className="stack"><label>WO No<input className="input" value={b.woNo} onChange={e=>setB({...b,woNo:e.target.value})} placeholder="WO-0001"/></label>{!id&&<label>BOM<select className="select" value={b.bomId} onChange={e=>setB({...b,bomId:e.target.value})}>{boms.map(x=><option key={x.id} value={x.id}>{x.bom_no} — {x.name}</option>)}</select></label>}<div className="grid two"><label>Planned Qty<input className="input" type="number" step="0.0001" value={b.plannedQty} onChange={e=>setB({...b,plannedQty:e.target.value})}/></label><label>WO Date<input className="input" type="date" value={b.woDate} onChange={e=>setB({...b,woDate:e.target.value})}/></label></div><label>Gudang<select className="select" value={b.warehouseName} onChange={e=>setB({...b,warehouseName:e.target.value})}><option value="">-- pilih gudang --</option>{warehouses.map(x=><option key={x.id||x.name} value={x.name}>{x.name}</option>)}</select></label><label>Catatan<textarea className="textarea" value={b.notes} onChange={e=>setB({...b,notes:e.target.value})}/></label></div></div>
 {id&&<><div className="card"><h2 className="section-title">Material WO</h2>{materials.map((m:any,i:number)=><div className="grid wo-detail-grid" key={i}><div><b>{m.itemNo}</b><div className="small muted">{m.itemName}</div></div><input className="input" type="number" step="0.0001" value={m.qty} onChange={e=>{const x=[...materials];x[i]={...m,qty:e.target.value};setMaterials(x)}}/><input className="input" value={m.unit} onChange={e=>{const x=[...materials];x[i]={...m,unit:e.target.value};setMaterials(x)}}/></div>)}</div><div className="card"><h2 className="section-title">Biaya WO</h2>{costs.map((k:any,i:number)=><div className="grid three" key={i}><input className="input" value={k.costName} onChange={e=>{const x=[...costs];x[i]={...k,costName:e.target.value};setCosts(x)}}/><input className="input" value={k.accountNo} onChange={e=>{const x=[...costs];x[i]={...k,accountNo:e.target.value};setCosts(x)}}/><input className="input" type="number" step="0.01" value={k.amount} onChange={e=>{const x=[...costs];x[i]={...k,amount:e.target.value};setCosts(x)}}/></div>)}</div></>}
 <div className="row"><button className="btn green" onClick={save}>{id?'Update WO':'Create WO from BOM'}</button>{msg&&<div className="muted">{msg}</div>}</div></div>
}
